import type { Metadata } from "next";
import { buildMetadata } from "@/lib/metadata";
import LegalPage, { type LegalSection } from "@/components/legal/legal-page";
import Link from "next/link";

export const metadata: Metadata = buildMetadata({
  title: "Terms of Service",
  description:
    "Read Zephio's Terms of Service to understand the rules and guidelines for using our AI web design platform.",
  path: "/terms",
  noIndex: false,
});

const sections: LegalSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: (
      <>
        <p>
          By accessing or using Zephio ("the Service"), you agree to be bound by these Terms of
          Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
        </p>
        <p>
          These Terms constitute a legally binding agreement between you and Zephio ("we," "us," or
          "our"). We reserve the right to update these Terms at any time. Continued use of the
          Service after changes constitutes acceptance of the revised Terms.
        </p>
        <div className="highlight-box">
          <strong>Plain English:</strong> Using Zephio means you agree to these rules. We'll notify
          you of significant changes via email.
        </div>
      </>
    ),
  },
  {
    id: "description",
    title: "Description of Service",
    content: (
      <>
        <p>
          Zephio is an AI-powered web design platform that enables users to generate, edit, and
          export website designs through natural language prompts. The Service includes:
        </p>
        <ul>
          <li>AI-generated HTML/CSS web page designs</li>
          <li>A canvas editor for reviewing and refining generated pages</li>
          <li>Export functionality to download designs as HTML files</li>
          <li>Public preview links for sharing designs</li>
          <li>Project management tools for organizing your designs</li>
        </ul>
        <p>
          We use third-party AI models to power generation features. The quality, accuracy, and
          appropriateness of AI-generated content may vary.
        </p>
      </>
    ),
  },
  {
    id: "accounts",
    title: "User Accounts",
    content: (
      <>
        <p>
          To access most features of the Service, you must create an account. You agree to:
        </p>
        <ul>
          <li>Provide accurate, current, and complete information during registration</li>
          <li>Maintain the security of your password and account credentials</li>
          <li>Promptly notify us of any unauthorized use of your account</li>
          <li>Accept responsibility for all activities that occur under your account</li>
        </ul>
        <p>
          You must be at least 16 years old to create an account. By creating an account, you
          represent that you meet this age requirement.
        </p>
        <p>
          We reserve the right to suspend or terminate accounts that violate these Terms, engage in
          fraudulent activity, or remain inactive for an extended period.
        </p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    content: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Generate content that is illegal, harmful, threatening, or abusive</li>
          <li>Infringe on the intellectual property rights of others</li>
          <li>Create phishing pages, malware distribution sites, or fraudulent content</li>
          <li>Attempt to reverse-engineer, scrape, or extract our AI models or systems</li>
          <li>Circumvent usage limits, rate limits, or access controls</li>
          <li>Resell or sublicense access to the Service without our written consent</li>
          <li>Use automated tools to generate content at scale beyond your plan limits</li>
          <li>Impersonate any person or entity or misrepresent your affiliation</li>
        </ul>
        <p>
          We reserve the right to remove any content and suspend any account that violates these
          guidelines, at our sole discretion.
        </p>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: (
      <>
        <h3>Your Content</h3>
        <p>
          You retain ownership of the content you provide as input (prompts, images, text). By
          using the Service, you grant us a limited, non-exclusive license to process your inputs
          solely to provide the Service.
        </p>
        <h3>Generated Output</h3>
        <p>
          Subject to your compliance with these Terms and payment of applicable fees, you own the
          HTML/CSS output generated by Zephio for your account. You may use, modify, and distribute
          generated designs for any lawful purpose, including commercial use.
        </p>
        <h3>Our Platform</h3>
        <p>
          The Zephio platform, including its software, design, trademarks, and underlying AI
          systems, remains our exclusive property. Nothing in these Terms transfers ownership of
          our platform to you.
        </p>
        <div className="highlight-box">
          <strong>Plain English:</strong> What you create is yours. Our platform is ours. Don't
          copy or resell our software.
        </div>
      </>
    ),
  },
  {
    id: "payments",
    title: "Payments & Subscriptions",
    content: (
      <>
        <p>
          Zephio offers a free tier and paid subscription plans. By subscribing to a paid plan, you
          agree to the following:
        </p>
        <ul>
          <li>
            <strong>Billing:</strong> Subscriptions are billed monthly or annually in advance.
            Payments are processed securely via Stripe.
          </li>
          <li>
            <strong>Auto-renewal:</strong> Subscriptions automatically renew unless cancelled
            before the renewal date.
          </li>
          <li>
            <strong>Cancellation:</strong> You may cancel at any time. Access continues until the
            end of the current billing period. No partial refunds are issued for unused time.
          </li>
          <li>
            <strong>Refunds:</strong> We offer a 7-day money-back guarantee for first-time
            subscribers. Contact{" "}
            <a href="mailto:support@zephio.app">support@zephio.app</a> within 7 days of your
            first charge.
          </li>
          <li>
            <strong>Price changes:</strong> We will provide at least 30 days' notice before
            changing subscription prices.
          </li>
        </ul>
        <p>
          Free tier usage is subject to monthly generation limits. Limits reset on the first day
          of each calendar month.
        </p>
      </>
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers & Limitations",
    content: (
      <>
        <p>
          The Service is provided "as is" and "as available" without warranties of any kind,
          express or implied. We do not warrant that:
        </p>
        <ul>
          <li>The Service will be uninterrupted, error-free, or secure</li>
          <li>AI-generated content will be accurate, complete, or suitable for your purpose</li>
          <li>Generated designs will be free from third-party intellectual property claims</li>
        </ul>
        <p>
          To the maximum extent permitted by law, Zephio's total liability for any claims arising
          from your use of the Service shall not exceed the amount you paid us in the 12 months
          preceding the claim.
        </p>
        <p>
          We are not liable for indirect, incidental, special, consequential, or punitive damages,
          including loss of profits, data, or goodwill.
        </p>
      </>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    content: (
      <>
        <p>
          Either party may terminate the agreement at any time. You may delete your account from
          your account settings. We may suspend or terminate your access if you violate these Terms.
        </p>
        <p>Upon termination:</p>
        <ul>
          <li>Your right to access the Service ceases immediately</li>
          <li>
            We will retain your data for 30 days, after which it may be permanently deleted
          </li>
          <li>
            You may request an export of your generated designs before account deletion
          </li>
          <li>Provisions that by their nature should survive termination will remain in effect</li>
        </ul>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law",
    content: (
      <>
        <p>
          These Terms are governed by and construed in accordance with applicable law. Any disputes
          arising from these Terms or your use of the Service shall be resolved through binding
          arbitration, except where prohibited by law.
        </p>
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining provisions
          will continue in full force and effect.
        </p>
        <p>
          These Terms constitute the entire agreement between you and Zephio regarding the Service
          and supersede all prior agreements.
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      badge="Legal"
      title="Terms of Service"
      subtitle="Please read these terms carefully before using Zephio. They govern your access to and use of our AI web design platform."
      effectiveDate="January 1, 2025"
      lastUpdated="April 14, 2026"
      sections={sections}
    />
  );
}
